name: Build success on PR

on:
  pull_request:
    branches:
      - main
      - jack

jobs:
  build:
    name: Build project 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js v24
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
          cache: 'yarn'

      - name: Install Yarn Dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: packages/db
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build Project
        run: yarn build
